# Generated by Django 2.0.13 on 2019-04-25 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=100)),
                ('dataNasc', models.DateField()),
                ('cargaH', models.CharField(max_length=2)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEnt1', models.DateTimeField()),
                ('horaSaida1', models.DateTimeField()),
                ('horaEnt2', models.DateTimeField()),
                ('horaSaida2', models.DateTimeField()),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crudpoints.Funcionario')),
            ],
        ),
    ]
