# Generated by Django 2.0.13 on 2019-04-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pis',
            field=models.CharField(default=' ', max_length=11),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(default=' ', max_length=8),
        ),
    ]
