# Generated by Django 2.0.13 on 2019-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0002_auto_20190428_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='horaEnt1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='horaEnt2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='horaSaida1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='horaSaida2',
            field=models.TimeField(),
        ),
    ]
