# Generated by Django 2.0.13 on 2019-04-29 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0003_auto_20190428_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 23, 27, 57, 471920)),
        ),
    ]
