# Generated by Django 2.0.13 on 2019-04-29 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0004_ponto_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 0, 15, 28, 690496)),
        ),
    ]
