# Generated by Django 2.0.13 on 2019-04-29 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0005_auto_20190429_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 13, 6, 17, 683673)),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudpoints.Funcionario'),
        ),
    ]
