# Generated by Django 2.0.13 on 2019-05-14 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0007_auto_20190429_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 19, 27, 6, 191763)),
        ),
    ]
