# Generated by Django 2.0.13 on 2019-05-14 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0008_auto_20190514_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 19, 49, 45, 129345)),
        ),
    ]
