# Generated by Django 2.0.13 on 2019-06-23 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpoints', '0009_auto_20190514_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=datetime.datetime(2019, 6, 23, 17, 45, 45, 483318)),
        ),
    ]
